CREATE OR REPLACE
 
FUNCTION FUNC_INSERE_PRODUTO (P_ID IN PRODUTO_AYM.ID_PROD%TYPE,
                         P_NOME IN PRODUTO_AYM.NOME%TYPE ,
                         P_PRECO_VENDA IN PRODUTO_AYM.PRECO_VENDA%TYPE,
                         P_ESTOQUE IN PRODUTO_AYM.ESTOQUE%TYPE
                          )
RETURN VARCHAR2
 
IS
      V_NOME_EXISTE NUMBER(1);
      V_ID_EXISTE NUMBER(1);
BEGIN
 
      SELECT COUNT(*) INTO V_NOME_EXISTE 
      FROM PRODUTO_AYM WHERE  NOME = P_NOME; 
      SELECT COUNT(*) INTO V_ID_EXISTE
      FROM PRODUTO_AYM WHERE ID_PROD = P_ID;  
 
 
        IF  P_ESTOQUE > 1000 OR P_ESTOQUE < 0 THEN -- ESTOQUE FORA DE PARAMÊTRO
            RETURN '-994';
 
        ELSIF P_PRECO_VENDA > 9999999999.99 OR P_PRECO_VENDA < 0 THEN -- PRECO FORA DE PARAMÊTRO 
            RETURN '-995';
 
        ELSIF P_NOME IS NULL OR LENGTH(P_NOME) > 120 THEN-- NOME FORA DE PARAMÊTRO 
            RETURN '-996';
 
        ELSIF P_ID > 99999 OR P_ID < 0 THEN -- VERIFICA ID FORA DE PARAMÊTROS 
            RETURN '-997';
 
 
        ELSIF V_NOME_EXISTE = 1 THEN -- NOME JÁ EXISTE
            RETURN '-998';  
 
        ELSIF V_ID_EXISTE = 1 THEN  -- ID JÁ EXISTE
            RETURN '-999';
 
        ELSE 
        INSERT INTO PRODUTO_AYM(ID_PROD, NOME, PRECO_VENDA, ESTOQUE) 
        VALUES(P_ID, P_NOME, P_PRECO_VENDA, P_ESTOQUE);
        RETURN '0';
 
      END IF;
END;
