CREATE OR REPLACE
FUNCTION FUNC_RETDEPT (P_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE)
RETURN VARCHAR2
 
IS
      V_DEPT_ID departments.DEPARTMENT_ID%TYPE;
      V_DEPT_NAME departments.DEPARTMENT_NAME%TYPE;
      V_QTDE NUMBER(1);
BEGIN
 
    SELECT COUNT(*) INTO V_QTDE
          FROM EMPLOYEES WHERE EMPLOYEE_ID = P_ID;
      IF V_QTDE = 1 THEN  
            SELECT D.DEPARTMENT_NAME INTO V_DEPT_NAME
            FROM EMPLOYEES E
            LEFT JOIN DEPARTMENTS D
            ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
        RETURN V_DEPT_NAME;
      ELSE
        RETURN '-9999';
      END IF;
END;
