-- simulação de ajuste de salario. salary * x
CREATE OR REPLACE 
FUNCTION FUNC_SIMULASALARIO  (P_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE,
                              P_PERC IN NUMBER)
RETURN NUMBER
IS
      V_SALARY_ATUAL EMPLOYEES.SALARY%TYPE;
      V_SALARY_SIMULADO EMPLOYEES.SALARY%TYPE; 
      V_QTDE NUMBER(1);
BEGIN
    IF P_PERC > 0 AND P_PERC <=15 THEN
        SELECT COUNT(*) INTO V_QTDE
          FROM EMPLOYEES WHERE EMPLOYEE_ID = P_ID;
        IF V_QTDE = 1 THEN
            SELECT SALARY INTO V_SALARY_ATUAL
               FROM EMPLOYEES WHERE EMPLOYEE_ID = P_ID;   
            V_SALARY_SIMULADO := (V_SALARY_ATUAL * ((100 + P_PERC)/100));   
            RETURN V_SALARY_SIMULADO;
        ELSE
          RETURN -2;
        END IF;
    ELSE
        RETURN -1;
    END IF;
END;
 
--Exemplo de consulta 
DECLARE 
  RETORNO NUMBER;
BEGIN
  RETORNO :=   FUNC_SIMULASALARIO(105,9);  
  DBMS_OUTPUT.PUT_LINE ('Retorno: ' || RETORNO);
END;
